---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1002
      - PGID=1004
      - TZ=America/Chicago
    volumes:
      - /opt/dockerized/sonarr/config:/config
      - /mnt/media/public/plex/series:/tv
      - /mnt/media/torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
