---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1002
      - PGID=1004
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=claim-AcCdCUwsC5U3gzibQAmc
    volumes:
      - /mnt/media/public/plex/library:/config
      - /mnt/media/public/plex/series:/tv
      - /mnt/media/public/plex/movies:/movies
      - /mnt/media/public/plex/anime:/anime
    restart: unless-stopped
