---
version: "2"
services:
  sonarr:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1002
      - PGID=1004
      - TZ=America/Chicago
    volumes:
      - /opt/dockerized/jackett:/config
      - /mnt/media/torrent-files:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
