---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr-kids
    environment:
      - PUID=1002
      - PGID=1004
      - TZ=America/Chicago
    volumes:
      - /opt/dockerized/sonarr-kids/config:/config
      - /mnt/media/public/plex/kids:/tv
      - /mnt/media/torrent-downloads:/downloads
    ports:
      - 8987:8989
    restart: unless-stopped
