---
version: "2"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1002
      - PGID=1004
      - TZ=America/Chicago
    volumes:
      - /opt/dockerized/lidarr/config:/config
      - /mnt/media/public/plex/music:/music
      - /mnt/media/torrent-downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
